platform :ios, '9.0'

target 'MapsDirection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacesAPI'
  pod 'SwiftyJSON'
  pod 'UberRides', '~> 0.9'


  # Pods for Maps Direction

end
